site_name: RAP Community of Practice
# site_url: https://example.com
repo_url: https://github.com/NHSDigital/rap-community-of-practice
repo_name: RAP Community of Practice
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - search
  - mkdocs-jupyter:
      include_source: True
      theme: dark
  - tags:
      tags_file: tags.md
nav:
  - Home: index.md
  - Tags: tags.md
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: indigo
  font:
    text: Arial
  logo: images/logo/nhs-blue-on-white.jpg
  favicon: images/favicon/favicon.ico
  features:
    - search.share
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  icon:
    admonition:
      <type>: material/alert
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - tables
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra:
  generator: false
copyright: Copyright &copy; 2025 Crown Copyright (NHS England)
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
watch:
  - overrides
